import { expect, request } from 'chai';
import 'mocha';
import server from '../..';
import { Applicant } from '../user/applicant';
import { Recruiter } from '../user/recruiter';
import { Meeting } from './meeting';
import { MeetingNotes } from './meetingNotes';
import chai = require('chai');
import chaiHttp = require('chai-http');
import { DBClient } from '../../db/dbClient';
import { testDatabaseName, test } from '../../.config';

// To use test HTTP API
chai.use(chaiHttp);

// Test Meeting class
describe('Meeting', () => {

    it('constructor', () => {
        expect(new Meeting(new Recruiter("", "", "", ""), new Applicant("", "", "", ""), "", "")).to.be.an.instanceOf(Meeting);
    });

    it('getLink - should get link created for meeting by WebRTCAdapter', () => {
        // add more to this test when there are some constraints on what type of link is generated by WebRTCAdapter
        expect(new Meeting(new Recruiter("", "", "", ""), new Applicant("", "", "", ""), "", "").getLink());
    });
});

// Test MeetingNotes
describe('MeetingNotes', () => {

    it('constructor', () => {
        expect(new MeetingNotes("", "", "", "", "")).to.be.an.instanceOf(MeetingNotes);
    });

    it('serialize - returns itself', () => {
        expect((new MeetingNotes("", "", "", "", "")).serialize()).to.be.an.instanceOf(MeetingNotes);
    });
});

// Test MeetingNotes API

// dummy meeting note to use
const noteA = new MeetingNotes("rec-1", "app-1", "company-1", "careerFair-1", "")
const noteB = new MeetingNotes("rec-1", "app-2", "company-1", "careerFair-1", "");
describe('MeetingNotes API (/meetingNotes)', () => {

    // Reset database after every test
    before(async () => {
        DBClient.connect();
        await DBClient.mongoClient.db(testDatabaseName).dropDatabase();
    });

    afterEach(async () => {
        await DBClient.mongoClient.db(testDatabaseName).dropDatabase();
    });

    const prefix = "/meetingNotes"
    it('POST / - creates new note', async () => 
    {
        await request(server).post(prefix + "/").send(noteA)
            .then(
                async res => 
                {
                    expect(res.body).to.be.a('object');
                    expect(res.body.body.success).to.be.true;
                    expect(await MeetingNotes.db.count({})).to.equal(1);
                }
            );
    });
    /*
    it('GET /company/:companyId - gets all meeting notes for a company ', (done) => 
    {
        request(server).post(prefix + "/")
            .then(
                res => 
                {
                    expect(res.body.sucesss).to.be.true;
                    expect(MeetingNotes.db.count({})).to.equal(1);
                }
            )
            .then(() => done(), done);
    });

    it('GET /company/:companyId/applicant/:applicantId - gets all notes for company on a given applicant', (done) => 
    {
        request(server).post(prefix + "/")
            .then(
                res => 
                {
                    expect(res.body.sucesss).to.be.true;
                    expect(MeetingNotes.db.count({})).to.equal(1);
                }
            )
            .then(() => done(), done);
    });

    it('GET /company/:companyId/careerFair/:careerFairId - gets all notes for company from a given career fair', (done) => 
    {
        request(server).post(prefix + "/")
            .then(
                res => 
                {
                    expect(res.body.sucesss).to.be.true;
                    expect(MeetingNotes.db.count({})).to.equal(1);
                }
            )
            .then(() => done(), done);
    });

    it('GET /company/:companyId/careerfair/:careerFairId/applicant/:applicantId', (done) => 
    {
        request(server).post(prefix + "/")
            .then(
                res => 
                {
                    expect(res.body.sucesss).to.be.true;
                    expect(MeetingNotes.db.count({})).to.equal(1);
                }
            )
            .then(() => done(), done);
    });

    it('UPDATE /company/:companyId/careerfair/:careerFairId/applicant/:applicantId', (done) => 
    {
        request(server).post(prefix + "/")
            .then(
                res => 
                {
                    expect(res.body.sucesss).to.be.true;
                    expect(MeetingNotes.db.count({})).to.equal(1);
                }
            )
            .then(() => done(), done);
    });

    it('DELETE /company/:companyId/careerfair/:careerFairId/applicant/:applicantId', (done) => 
    {
        request(server).post(prefix + "/")
            .then(
                res => 
                {
                    expect(res.body.sucesss).to.be.true;
                    expect(MeetingNotes.db.count({})).to.equal(1);
                }
            )
            .then(() => done(), done);
    });
    */
});